config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/contact' => 'contact#index', :as => 'contact'
  get 'welcome/index'
  get '/cv' => 'cv#index', :as => 'cv'

  resources :educations
  resources :jobs
  resources :projects

  resources :skills do
    resources :activeties
  end

  resources :articles do
    resources :comments
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.admin_role?
      can :manage, :all
    end
    if user.user_role?
      can :create, Comment
      can :read, Comment
      can :read, Article
      can :read, Skill
      can :read, Activety
      can :read, Project
      can :read, Job
      can :read, Education
    end

  end
end

app/models/activety.rb
class Activety < ApplicationRecord
  belongs_to :skill
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 5 }

  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :activeties, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @jobs = Job.all
    @edus = Education.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index, :show]
  load_and_authorize_resource
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company, :start_date, :end_date, :link, :position, :current)
    end
end

app/helpers/activeties_helper.rb
module ActivetiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    current_route = Rails.application.routes.recognize_path(path)
    "current" if current_page?(path) or params[:controller] == current_route[:controller]
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
        auto_link: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date, {:include_blank => true, :default => nil} %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, {:include_blank => true, :default => nil} %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :current %>
    <%= f.check_box :current %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Link</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.company %></td>
        <td><%= job.start_date %></td>
        <td><%= job.end_date %></td>
        <td><%= job.link %></td>
        <td><%= job.position %></td>
        <td><%= link_to 'Show', job %></td>
        <% if can? :manage, :all %>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end  %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, :all %>
  <%= link_to 'New Job', new_job_path %>
<% end  %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @job.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @job.end_date %>
</p>

<p>
  <strong>Link:</strong>
  <%= @job.link %>
</p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>
<% if can? :manage, :all %>
  <%= link_to 'Edit', edit_job_path(@job) %>
<% end %>

<%= link_to 'Back', jobs_path %>