config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/contact' => 'contact#index', :as => 'contact'
  get 'welcome/index'
  get '/cv' => 'cv#index', :as => 'cv'

  resources :educations
  resources :jobs
  resources :projects

  resources :skills do
    resources :activeties
  end

  resources :articles do
    resources :comments
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.admin_role?
      can :manage, :all
    end
    if user.user_role?
      can :create, Comment
      can :read, Comment
      can :read, Article
      can :read, Skill
      can :read, Activety
      can :read, Project
      can :read, Job
      can :read, Education
    end

  end
end

app/models/activety.rb
class Activety < ApplicationRecord
  belongs_to :skill
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 5 }

  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :activeties, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @jobs = Job.all
    @edus = Education.all
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index, :show]
  load_and_authorize_resource

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:title, :description)
    end
end

app/helpers/activeties_helper.rb
module ActivetiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    current_route = Rails.application.routes.recognize_path(path)
    "current" if current_page?(path) or params[:controller] == current_route[:controller]
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
        auto_link: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/skills/_form.html.erb
<%= form_for(skill) do |f| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h1>skills</h1>

<% @skills.each do |skill|  %>
  <h2><%= skill.title %></h2>
    <p>
      <%= skill.description %>
      <% skill.activeties.each do |act| %>
        <ul>
          <li><%= act.name %></li>
        </ul>
    <% end %>
    </p>
    <%= link_to 'Show', skill_path(skill) %>
<% end %>


<% if can? :manage, :all %>
  <%= link_to 'New Skill', new_skill_path %>
<% end %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<h1><%= @skill.title %></h1>

<h2>Skill Header</h2>
<p>
  <%= @skill.description %>
</p>

<h2>Activities</h2>

<%= render @skill.activeties %>
<% if can? :manage, :all %>

  <h2>Add an activity:</h2>
  <%= render :partial => 'activeties/form' %>

<% end %>

<% if can? :manage, :all %>
  <%= link_to 'Edit', edit_skill_path(@skill) %>
<% end  %>
<%= link_to 'Back', skills_path %>