config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/contact' => 'contact#index', :as => 'contact'
  get 'welcome/index'
  get '/cv' => 'cv#index', :as => 'cv'

  resources :educations
  resources :jobs
  resources :projects

  resources :skills do
    resources :activeties
  end

  resources :articles do
    resources :comments
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.admin_role?
      can :manage, :all
    end
    if user.user_role?
      can :create, Comment
      can :read, Comment
      can :read, Article
      can :read, Skill
      can :read, Activety
      can :read, Project
      can :read, Job
      can :read, Education
    end

  end
end

app/models/activety.rb
class Activety < ApplicationRecord
  belongs_to :skill
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 5 }

  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :activeties, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @jobs = Job.all
    @edus = Education.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index, :show]
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :link)
    end
end

app/helpers/activeties_helper.rb
module ActivetiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    current_route = Rails.application.routes.recognize_path(path)
    "current" if current_page?(path) or params[:controller] == current_route[:controller]
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
        auto_link: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>work</h1>

<% @projects.each do |project|  %>
  <h2><%= project.title %></h2>
    <p>
      <%= project.description.truncate_words(50) %><br>
      <%= link_to 'read more', project %>
      <%= link_to 'see on github', project.link, :target => "_blank" %>
    </p>

    <%= image_tag('project.png', class: 'img-responsive') %>
<% end %>

<% if can? :manage, :all %>
  <%= link_to 'New Project', new_project_path %>
<% end  %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<span class="col-md-6"><h1 class="title"><%= @project.title %></h1></span>

<div class="content-item">
  <div class="title-block col-md-12">
    <span class="col-md-8"><h2>Description</h2></span>
  </div>
  <div class="item-block col-md-10">
    <p>
      <%= @project.description %><br>
    <div class="item-link">
      <%= link_to 'Back', projects_path %>
    </div>
    </p>
  </div>
</div>

<% if can? :manage, :all %>
  <%= link_to 'Edit', edit_project_path(@project) %>
<% end %>