config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/contact' => 'contact#index', :as => 'contact'
  get 'welcome/index'
  get '/cv' => 'cv#index', :as => 'cv'

  resources :educations
  resources :jobs
  resources :projects

  resources :skills do
    resources :activeties
  end

  resources :articles do
    resources :comments
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.admin_role?
      can :manage, :all
    end
    if user.user_role?
      can :create, Comment
      can :read, Comment
      can :read, Article
      can :read, Skill
      can :read, Activety
      can :read, Project
      can :read, Job
      can :read, Education
    end

  end
end

app/models/activety.rb
class Activety < ApplicationRecord
  belongs_to :skill
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 5 }

  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :activeties, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @jobs = Job.all
    @edus = Education.all
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:name, :school, :location, :start_date, :end_date, :diploma, :current)
    end
end

app/helpers/activeties_helper.rb
module ActivetiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    current_route = Rails.application.routes.recognize_path(path)
    "current" if current_page?(path) or params[:controller] == current_route[:controller]
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
        auto_link: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/educations/_form.html.erb
<%= form_for(education) do |f| %>
  <% if education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :school %>
    <%= f.text_field :school %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date, {:include_blank => true, :default => nil} %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, {:include_blank => true, :default => nil} %>
  </div>

  <div class="field">
    <%= f.label :diploma %>
    <%= f.check_box :diploma %>
  </div>

  <div class="field">
    <%= f.label :current %>
    <%= f.check_box :current %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing Education</h1>

<%= render 'form', education: @education %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Educations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>School</th>
      <th>Location</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Diploma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.name %></td>
        <td><%= education.school %></td>
        <td><%= education.location %></td>
        <td><%= education.start_date %></td>
        <td><%= education.end_date %></td>
        <td><%= education.diploma %></td>
        <td><%= link_to 'Show', education %></td>
        <% if can? :manage, :all %>
          <td><%= link_to 'Edit', edit_education_path(education) %></td>
          <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, :all %>
  <%= link_to 'New Education', new_education_path %>
<% end  %>

app/views/educations/new.html.erb
<h1>New Education</h1>

<%= render 'form', education: @education %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @education.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @education.school %>
</p>

<p>
  <strong>Location:</strong>
  <%= @education.location %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @education.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @education.end_date %>
</p>

<p>
  <strong>Diploma:</strong>
  <%= @education.diploma %>
</p>
<% if can? :manage, :all %>
  <%= link_to 'Edit', edit_education_path(@education) %>
<% end  %>
<%= link_to 'Back', educations_path %>